from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import list_alien_race_names, delete_alien_race_name, update_alien_race_name, create_alien_race_name, \
    list_starship_problems, delete_starship_problem, list_rumors, delete_rumor, update_rumor, create_rumor

app_name = "harshrealmfe"

urlpatterns = [
                  path('', views.index, name='index'),
                  path('alien-race-names/',
                       list_alien_race_names,
                       name="list_alien_race_names"),
                  path('alien-race-names/<int:id>/delete/',
                       delete_alien_race_name,
                       name='delete_alien_race_name'),
                  path('alien-race-names/<int:id>/update/',
                       update_alien_race_name,
                       name='update_alien_race_name'),
                  path('alien-race-names/create/',
                       create_alien_race_name,
                       name="create_alien_race_name"),
                  path('mercs-for-hire/',
                       views.list_mercs_for_hire,
                       name='list_mercs_for_hire'),
                  path('mercs-for-hire/<int:id>/delete/',
                       views.delete_merc_for_hire,
                       name='delete_merc_for_hire'),
                  path('mercs-for-hire/<int:id>/update/',
                       views.update_merc_for_hire,
                       name='update_merc_for_hire'),
                  path('mercs-for-hire/create/',
                       views.create_merc_for_hire,
                       name='create_merc_for_hire'),
                  path('starship-problems/',
                       list_starship_problems,
                       name='list_starship_problems'),
                  path('starship-problems/<int:id>/delete/',
                       delete_starship_problem,
                       name='delete_starship_problem'),
                  path('starship-problems/<int:id>/update/',
                       views.update_starship_problem,
                       name='update_starship_problem'),
                  path('starship-problems/create/',
                       views.create_starship_problem,
                       name='create_starship_problem'),
                  path('rumors/',
                       list_rumors,
                       name='list_rumors'),
                  path('rumors/<int:id>/delete/',
                       delete_rumor,
                       name="delete_rumor"),
                  path('rumors/<int:id>/update/', update_rumor, name="update_rumor"),
                  path('rumors/create/', create_rumor, name="create_rumor"),
                  path('starship-names/', views.list_starship_names, name='list_starship_names'),
                  path('starship-names/<int:id>/delete/', views.delete_starship_name, name='delete_starship_name'),
                  path('starship-names/<int:id>/update/', views.update_starship_name, name='update_starship_name'),
                  path('starship-names/create/', views.create_starship_name, name='create_starship_name'),
                  path('random-items/', views.list_random_items, name='list_random_items'),
                  path('uselses-items/<int:id>/delete/', views.delete_random_item, name='delete_random_item'),
                  path('random-items/<int:id>/update/', views.update_random_item, name='update_random_item'),
                  path('random-items/create/', views.create_random_item, name='create_random_item'),
                  path('odd-situations/', views.list_odd_situations, name='list_odd_situations'),
                  path('odd-situations/<int:id>/delete/', views.delete_odd_situation, name='delete_odd_situation'),
                  path('odd-situations/<int:id>/update/', views.update_odd_situation, name='update_odd_situation'),
                  path('odd-situations/create/', views.create_odd_situation, name='create_odd_situation'),
                  path('reasons-characters-are-together/', views.list_reasons_characters_are_together,
                       name='list_reasons_characters_are_together'),
                  path('reasons-characters-are-together/<int:id>/delete/', views.delete_reason_characters_are_together,
                       name='delete_reason_characters_are_together'),
                  path('reasons-characters-are-together/<int:id>/update/', views.update_reason_characters_are_together,
                       name='update_reason_characters_are_together'),
                  path('reasons-characters-are-together/create/', views.create_reason_characters_are_together,
                       name='create_reason_characters_are_together'),
                  path('mission-hooks/', views.list_mission_hooks, name='list_mission_hooks'),
                  path('mission-hooks/<int:id>/delete/', views.delete_mission_hook, name='delete_mission_hook'),
                  path('mission-hooks/<int:id>/update/', views.update_mission_hook, name='update_mission_hook'),
                  path('mission-hooks/create/', views.create_mission_hook, name='create_mission_hook'),
                  path('client/', views.client_window, name='client'),
                  path('client/new-msg/', views.receive_chat_msg, name='receive_chat_msg'),
                  path('client/create-session/', views.create_session, name='create_session'),
                  path('client/load-session/', views.load_session, name='load_session'),
                  path('banned-cargo/', views.list_banned_cargo, name='list_banned_cargo'),
                  path('banned-cargo/<int:id>/delete/', views.delete_banned_cargo, name='delete_banned_cargo'),
                  path('banned-cargo/<int:id>/update/', views.update_banned_cargo, name='update_banned_cargo'),
                  path('banned-cargo/create/', views.create_banned_cargo, name='create_banned_cargo'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
