[tool.poetry]
name = "web-ui"
version = "0.1.0"
description = ""
authors = ["cyrex"]
readme = "README.md"
packages = [{include = "web_ui"}]

[tool.poetry.dependencies]
python = "^3.10"
reflex = "^0.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
