# Generated by Django 4.2.1 on 2023-05-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlienRace',
            new_name='AlienRaceName',
        ),
    ]
