# Generated by Django 4.2.1 on 2023-05-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0002_rename_alienrace_alienracename'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercsForHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
