# Generated by Django 4.2.1 on 2023-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0003_mercsforhire'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarshipProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
