# Generated by Django 4.2.1 on 2023-05-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0004_starshipproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
