# Generated by Django 4.2.1 on 2023-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0007_uselessitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('situation', models.TextField()),
            ],
        ),
    ]
