# Generated by Django 4.2.1 on 2023-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0009_reasoncharactersaretogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('hook', models.TextField()),
            ],
        ),
    ]
