# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0012_alter_chatmessage_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='ChatSession',
        ),
    ]
