# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0013_rename_session_chatsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='session',
            new_name='chat_session',
        ),
    ]
