# Generated by Django 4.2.1 on 2023-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harshrealmfe', '0014_rename_session_chatmessage_chat_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_roll', models.IntegerField()),
                ('cargo', models.TextField()),
            ],
        ),
    ]
